name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: check compiler versions
      run: sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
      run: sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
      run: gcc -v && g++ -v && cmake --version
    #- name: make
    #  run: make
    #- name: make check
    #  run: make check
    #- name: make distcheck
    #  run: make distcheck
